name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  scripts:
    if: github.repository_owner == 'bombshell-dev'
    uses: bombshell-dev/automation/.github/workflows/run.yml@3a8b4a38fe464b0b51d14962ae416a169517fba9  # main as of 2026-05-12
    with:
      commands: >
        [
          "build",
          "types",
          "test",
          "deps"
        ]
