name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  format:
    if: github.repository_owner == 'bombshell-dev'
    uses: bombshell-dev/automation/.github/workflows/format.yml@3a8b4a38fe464b0b51d14962ae416a169517fba9  # main as of 2026-05-12
    permissions:
      contents: write
      pull-requests: write
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
